name: Build and deploy PHP and Python app to Azure Web App - QR-Track

on:
  push:
    branches:
      - Soban2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      # Setup Python environment and install dependencies
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure this is compatible with your app

      - name: Check if requirements.txt exists
        id: check_requirements
        uses: andstor/file-existence-action@v1
        with:
          files: 'requirements.txt'

      - name: Install Python dependencies if requirements.txt exists
        if: steps.check_requirements.outputs.files_exists == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Start Python Flask app
      - name: Start Python Flask app (Check if it works locally)
        run: |
          echo "Starting Python app"
          nohup python app.py &  # Make sure this is the correct command to start your Python app
        continue-on-error: true

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'QR-Track'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D7A68860B51D428FA6D796E799A8E2A2 }}
